version: "3.7"

services:
  
  nginx:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    #container_name: nginx
    image: nginx-inverseproxy-loadbalance-osrm:1.0
    build: ./nginx
    restart: unless-stopped
    depends_on:
      - osrm_col
    ports:
      - "80:80"
      - "443:443"
    networks:
      - net_osrm

  osrm_col:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    image: osrm_col:1.0
    build:
      context: ./osrm
      args:
        - REGIONAL_NAME=${OSRM_COL_REGIONAL_NAME}
        - COUNTRY_NAME=${OSRM_COL_COUNTRY_NAME}
    restart: always
    command: bash -c "osrm-routed --algorithm ch --max-table-size=100000 --max-viaroute-size=1000 --max-matching-size 1000 /data/${OSRM_COL_COUNTRY_NAME}.osrm"
    ports:
      - "5000"
    networks:
      - net_osrm

  osrm_chi:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    image: osrm_chi:1.0
    build:
      context: ./osrm
      args: 
        - REGIONAL_NAME=${OSRM_CHI_REGIONAL_NAME}
        - COUNTRY_NAME=${OSRM_CHI_COUNTRY_NAME}
    restart: always
    command: bash -c "osrm-routed --algorithm ch --max-table-size=100000 --max-viaroute-size=1000 --max-matching-size 1000 /data/${OSRM_CHI_COUNTRY_NAME}.osrm"
    ports:
      - "5000"
    networks:
      - net_osrm

  osrm_mex:
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    image: osrm_mex:1.0
    build:
      context: ./osrm
      args: 
        - REGIONAL_NAME=${OSRM_MEX_REGIONAL_NAME}
        - COUNTRY_NAME=${OSRM_MEX_COUNTRY_NAME}
    restart: always
    command: bash -c "osrm-routed --algorithm ch --max-table-size=100000 --max-viaroute-size=1000 --max-matching-size 1000 /data/${OSRM_MEX_COUNTRY_NAME}.osrm"
    ports:
      - "5000"
    networks:
      - net_osrm

networks:
  net_osrm: